version: '2'
services:
  edf:
    build: .
    devices:
      - /dev/mem
      - /dev/ttyAMA0
    cap_add:
      - SYS_RAWIO
    links:
      - mongodb
  mongodb:
    image: cretzel/rpi-mongodb
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
    driver: local
